default: &default
  adapter: postgresql
  encoding: unicode
  database: therapymessages
  pool: 16
  username: garthgaughan
  password: 
  host: localhost
  port: 5432

development:
  adapter: postgresql
  encoding: unicode
  database: therapymessages
  pool: 16
  username: garthgaughan
  password: 
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: therapymessages
  pool: 16
  username: garthgaughan
  password: 
  host: localhost
  port: 5432
